### ISSUE TITLE
substr raises exception in nosuffix

### ISSUE THREAD

**Issue by rsharris** [Kingsford-Group/splitsbt#6]
in util.cc, nosuffix() doesn't consider that the incoming string str may be shorter than suff.  When it is, end gets an invalid value which causes s.substr(end) to throw a std::out_of_range exception.

**Comment by rsharris** [comment]
The same is true for all the suffix tests in BF.cc.  For example, in  SBF::save(), if the filename is shorter than 15, an exception is raised.

**Comment by rsharris** [comment]
Probably also true in test_basename().

**Comment by rsharris** [comment]
I'm surprised C++ has no string.ends_with() function.  Looks like one has been added for C++20, but I wonder how many compilers are compliant with C++20 at this point.

**Comment by Bradsol** [comment]
Yeah this is definitely an element of sloppy code on my part. I have corrected the instances which will fail due to a poor choice in naming convention in BF.cc and the highlighted functions in util.cc. Ex: When the file name (sans suffix) is less then five letters long the 'union' checks will fail. You'll see these changes in the next commit. 

The other suffix checks aren't actually a problem (beyond being a very poor design choice) because files are loaded (and assigned a type) based upon an exact suffix chain. For example, load_bf_from_file kills the program if you don't provide either a 14, 4, 10, or 3 letter suffix defining general BF-type and union nodes are defined by the presence of the additional string 'union' immediately before the suffix.

**Comment by rsharris** [comment]
I may have hit the "other" suffix problem because I'm leaving the extension off my "bt count" command.

Be aware that both the manual (twice) and the in-program usage say the extension for the output file should be .bf.bv. But if you do that you get .bf.bv.sim.bf.bv (or at least I got that with some version of the code).  Then, for me, something downstream had an issue with that.  IIRC it was something trying to do a dynamic cast to (is it SBF*) and then telling me the file wasn't the right type.  Took me a while to notice it had created extra stuff in the extension.

So I removed the extension from my bt count command and things seemed to work -- the count command seems to have happily appended the .sim.bf.bv extension.  Since my only goal is to get it running for comparison, once I found that workaround I moved on and didn't dig any deeper.  I don't know if I'm supposed to provide the extension or not.

But in the example I was working with the leaves had longish names like experiment1. When I started using shorter names (like SRRxxxx) is when I started triggering the suffix exceptions.  And in trying to debug that I had the misfortune to use a short name like temp, and I think by doing so I hit a different suffix problem.

None of that really held me up -- well, at least not once I figured out what was causing the error.
